#pragma once

#ifdef CONFIG_IDF_TARGET_ESP32
#define CHANNEL_1_PIN GPIO_NUM_33
#define CHANNEL_2_PIN GPIO_NUM_25
#define CHANNEL_3_PIN GPIO_NUM_26
#define CHANNEL_4_PIN GPIO_NUM_27
#endif

#ifdef CONFIG_IDF_TARGET_ESP32C6
#define CHANNEL_1_PIN GPIO_NUM_20
#define CHANNEL_2_PIN GPIO_NUM_21
#define CHANNEL_3_PIN GPIO_NUM_22
#define CHANNEL_4_PIN GPIO_NUM_23
#endif